name: diy-client
ui: tape
browsers:
    - name: chrome
      version: latest
    - name: ie
      version: 9..latest
    - name: firefox
      version: latest
    - name: safari
      version: 5..latest
